import {
  Campaign,
  CommunicationProfile,
  ContactProfile,
  Lead,
  Notification,
  Order,
  Persona,
  TargetingProfile,
  User,
} from "./types";

export const users: User[] = [
  {
    id: "u1",
    name: "Sarah Mitchell",
    email: "sarah@advisorgroup.com",
    role: "client",
    company: "Mitchell Wealth Advisors",
  },
  {
    id: "u2",
    name: "James Rivera",
    email: "james@trailmap.io",
    role: "internal",
    company: "Trailmap",
  },
  {
    id: "u3",
    name: "Amanda Chen",
    email: "amanda@trailmap.io",
    role: "admin",
    company: "Trailmap",
  },
];

export const campaigns: Campaign[] = [
  {
    id: "c1",
    name: "Spring Retirement Workshop",
    type: "Workshop",
    status: "Active",
    startDate: "2026-04-10",
    endDate: "2026-04-10",
    location: "Hilton Downtown, Chicago",
    budget: 15000,
    spent: 8750,
    leads: 47,
    registrations: 62,
    advisor: "Sarah Mitchell",
    description:
      "A comprehensive retirement planning workshop targeting pre-retirees aged 55-70 in the greater Chicago area. Topics include Social Security optimization, tax-efficient withdrawal strategies, and estate planning basics.",
    confirmationMessage:
      "Thank you for registering! We look forward to seeing you at our Spring Retirement Workshop. Light refreshments will be served.",
    landingPageUrl: "https://events.trailmap.io/spring-retirement-2026",
    registrationUrl: "https://register.trailmap.io/spring-retirement-2026",
  },
  {
    id: "c2",
    name: "Tax Planning Webinar Series",
    type: "Webinar",
    status: "Active",
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    location: "Virtual (Zoom)",
    budget: 5000,
    spent: 2100,
    leads: 128,
    registrations: 215,
    advisor: "Sarah Mitchell",
    description:
      "A 4-part webinar series covering year-end tax planning strategies for high-net-worth individuals. Each session focuses on different aspects of tax optimization.",
    confirmationMessage:
      "You're registered for our Tax Planning Webinar Series! Check your email for Zoom links.",
    landingPageUrl: "https://events.trailmap.io/tax-planning-2026",
    registrationUrl: "https://register.trailmap.io/tax-planning-2026",
  },
  {
    id: "c3",
    name: "Estate Planning Dinner",
    type: "Dinner Event",
    status: "Scheduled",
    startDate: "2026-05-15",
    endDate: "2026-05-15",
    location: "Ruth's Chris Steak House, Naperville",
    budget: 12000,
    spent: 0,
    leads: 0,
    registrations: 34,
    advisor: "Sarah Mitchell",
    description:
      "An exclusive dinner event for qualified prospects interested in comprehensive estate planning. Limited to 40 attendees.",
    confirmationMessage:
      "You're confirmed for our exclusive Estate Planning Dinner! Dress code is business casual.",
    landingPageUrl: "https://events.trailmap.io/estate-dinner-2026",
    registrationUrl: "https://register.trailmap.io/estate-dinner-2026",
  },
  {
    id: "c4",
    name: "Women & Wealth Seminar",
    type: "Seminar",
    status: "Scheduled",
    startDate: "2026-05-22",
    endDate: "2026-05-22",
    location: "Marriott Conference Center, Oak Brook",
    budget: 8000,
    spent: 0,
    leads: 0,
    registrations: 18,
    advisor: "Sarah Mitchell",
    description:
      "A seminar focused on the unique financial challenges and opportunities for women. Covering investment strategies, retirement planning, and financial independence.",
    confirmationMessage:
      "Welcome to Women & Wealth! We're excited to have you join us for this empowering event.",
    landingPageUrl: "https://events.trailmap.io/women-wealth-2026",
    registrationUrl: "https://register.trailmap.io/women-wealth-2026",
  },
  {
    id: "c5",
    name: "Medicare & Social Security Workshop",
    type: "Workshop",
    status: "Ended",
    startDate: "2026-02-20",
    endDate: "2026-02-20",
    location: "Public Library, Schaumburg",
    budget: 6000,
    spent: 5800,
    leads: 31,
    registrations: 45,
    advisor: "Sarah Mitchell",
    description:
      "Educational workshop on Medicare enrollment, Social Security claiming strategies, and how they impact retirement income.",
    confirmationMessage: "See you at the workshop!",
    landingPageUrl: "https://events.trailmap.io/medicare-ss-2026",
    registrationUrl: "https://register.trailmap.io/medicare-ss-2026",
  },
  {
    id: "c6",
    name: "Lunch & Learn: Market Outlook",
    type: "Lunch & Learn",
    status: "Paused",
    startDate: "2026-04-25",
    endDate: "2026-04-25",
    location: "Corporate Office, Downtown Chicago",
    budget: 3000,
    spent: 500,
    leads: 8,
    registrations: 12,
    advisor: "Sarah Mitchell",
    description:
      "A casual lunch event discussing current market conditions and 2026 investment outlook for corporate employees.",
    confirmationMessage: "Lunch is on us! See you there.",
    landingPageUrl: "https://events.trailmap.io/lunch-learn-market-2026",
    registrationUrl: "https://register.trailmap.io/lunch-learn-market-2026",
  },
];

export const orders: Order[] = [
  {
    id: "ord-001",
    title: "Spring Retirement Workshop Campaign",
    type: "Workshop",
    status: "In Progress",
    budget: 15000,
    dateRangeStart: "2026-03-01",
    dateRangeEnd: "2026-04-10",
    numberOfEvents: 1,
    targetingProfile: "Pre-Retirees Chicago",
    targetAge: "55-70",
    targetIncome: "$100K+",
    targetRadius: "25 miles",
    campaignDetails:
      "Full-service retirement workshop campaign including direct mail, digital ads, and follow-up sequences. Focus on Social Security optimization and retirement income planning topics.",
    assetPreferences: ["Direct Mail", "Facebook Ads", "Landing Page", "Email Sequence"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-02-15",
    updatedAt: "2026-03-28",
  },
  {
    id: "ord-002",
    title: "Tax Planning Webinar Series - Q2",
    type: "Webinar",
    status: "Approved",
    budget: 5000,
    dateRangeStart: "2026-04-01",
    dateRangeEnd: "2026-04-30",
    numberOfEvents: 4,
    targetingProfile: "High Net Worth",
    targetAge: "45-65",
    targetIncome: "$250K+",
    targetRadius: "50 miles",
    campaignDetails:
      "4-part webinar series covering tax-loss harvesting, Roth conversions, and year-end planning strategies. Target affluent clients with complex tax situations.",
    assetPreferences: ["Google Ads", "LinkedIn Ads", "Landing Page", "Email Sequence"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-18",
  },
  {
    id: "ord-003",
    title: "Estate Planning Dinner - Ultra HNW",
    type: "Dinner Event",
    status: "Under Review",
    budget: 12000,
    dateRangeStart: "2026-04-01",
    dateRangeEnd: "2026-05-15",
    numberOfEvents: 1,
    targetingProfile: "Ultra HNW Prospects",
    targetAge: "50-70",
    targetIncome: "$500K+",
    targetRadius: "15 miles",
    campaignDetails:
      "Exclusive dinner event at Ruth's Chris for ultra-high-net-worth prospects. Focus on estate planning, trust strategies, and charitable giving. Limited to 40 attendees.",
    assetPreferences: ["Premium Mailer", "Personal Invitation", "Landing Page", "Phone Follow-up"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-10",
    updatedAt: "2026-03-27",
  },
  {
    id: "ord-004",
    title: "Women & Wealth Seminar - Oak Brook",
    type: "Seminar",
    status: "Submitted",
    budget: 8000,
    dateRangeStart: "2026-04-15",
    dateRangeEnd: "2026-05-22",
    numberOfEvents: 1,
    targetingProfile: "Women 45-65",
    targetAge: "45-65",
    targetIncome: "$150K+",
    targetRadius: "30 miles",
    campaignDetails:
      "Full-day seminar focusing on financial independence, investment strategies for women, and retirement planning. Partner with local women's business association for promotion.",
    assetPreferences: ["Facebook Ads", "Instagram Ads", "Direct Mail", "Email Sequence"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-18",
    updatedAt: "2026-03-18",
  },
  {
    id: "ord-005",
    title: "Medicare Workshop Follow-up Campaign",
    type: "Workshop",
    status: "Completed",
    budget: 6000,
    dateRangeStart: "2026-01-15",
    dateRangeEnd: "2026-02-20",
    numberOfEvents: 1,
    targetingProfile: "Pre-Retirees Suburban",
    targetAge: "60-72",
    targetIncome: "$75K+",
    targetRadius: "20 miles",
    campaignDetails:
      "Post-workshop nurture campaign targeting attendees and no-shows. Schedule one-on-one Medicare consultation appointments. Generated 31 qualified leads.",
    assetPreferences: ["Direct Mail", "Email Sequence", "Phone Follow-up"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-01-10",
    updatedAt: "2026-03-01",
  },
  {
    id: "ord-006",
    title: "Q3 Market Outlook Lunch & Learn",
    type: "Lunch & Learn",
    status: "Draft",
    budget: 3000,
    dateRangeStart: "2026-04-10",
    dateRangeEnd: "2026-04-25",
    numberOfEvents: 1,
    targetingProfile: "Corporate Employees",
    targetAge: "35-55",
    targetIncome: "$100K+",
    targetRadius: "10 miles",
    campaignDetails:
      "Lunch event at corporate office discussing 2026 market outlook, interest rate impacts, and portfolio rebalancing strategies. Target existing client employees.",
    assetPreferences: ["Email Invitation", "Landing Page"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-25",
    updatedAt: "2026-03-25",
  },
  {
    id: "ord-007",
    title: "Year-End Tax Strategy Webinar",
    type: "Webinar",
    status: "Processing",
    budget: 4500,
    dateRangeStart: "2026-10-01",
    dateRangeEnd: "2026-12-15",
    numberOfEvents: 3,
    targetingProfile: "High Net Worth",
    targetAge: "50-65",
    targetIncome: "$200K+",
    targetRadius: "National",
    campaignDetails:
      "3-part webinar series on tax-efficient investing, charitable giving strategies, and year-end portfolio review. Target clients with $500K+ in investable assets.",
    assetPreferences: ["Email Sequence", "LinkedIn Ads", "Landing Page", "Retargeting Ads"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-20",
    updatedAt: "2026-03-28",
  },
  {
    id: "ord-008",
    title: "Retirement Dreams Workshop",
    type: "Workshop",
    status: "Pending",
    budget: 9500,
    dateRangeStart: "2026-05-01",
    dateRangeEnd: "2026-05-30",
    numberOfEvents: 2,
    targetingProfile: "Pre-Retirees Chicago",
    targetAge: "55-68",
    targetIncome: "$125K+",
    targetRadius: "35 miles",
    campaignDetails:
      "Two-session workshop series: Session 1 - Retirement income planning, Session 2 - Healthcare & Social Security. Target couples approaching retirement.",
    assetPreferences: ["Direct Mail", "Facebook Ads", "Email Sequence", "Landing Page", "Phone Follow-up"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-22",
    updatedAt: "2026-03-26",
  },
  {
    id: "ord-009",
    title: "Business Owner Exit Planning Seminar",
    type: "Seminar",
    status: "Under Review",
    budget: 18000,
    dateRangeStart: "2026-06-01",
    dateRangeEnd: "2026-08-30",
    numberOfEvents: 3,
    targetingProfile: "Business Owners",
    targetAge: "50-65",
    targetIncome: "$250K+",
    targetRadius: "75 miles",
    campaignDetails:
      "Series for business owners exploring exit strategies, succession planning, and wealth preservation. Partner with local CPA and attorney firms for referrals.",
    assetPreferences: ["LinkedIn Ads", "Direct Mail", "Premium Mailer", "Webinar", "Phone Outreach"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-15",
    updatedAt: "2026-03-27",
  },
  {
    id: "ord-010",
    title: "Social Security Optimization Workshop",
    type: "Workshop",
    status: "Completed",
    budget: 7500,
    dateRangeStart: "2025-11-01",
    dateRangeEnd: "2025-12-15",
    numberOfEvents: 4,
    targetingProfile: "Pre-Retirees Suburban",
    targetAge: "62-70",
    targetIncome: "$60K+",
    targetRadius: "25 miles",
    campaignDetails:
      "4 workshops across the suburbs covering when to claim Social Security, spousal benefits, and coordination with retirement accounts. Great lead generator.",
    assetPreferences: ["Direct Mail", "Local Newspaper Ads", "Email Sequence", "Landing Page"],
    advisor: "Sarah Mitchell",
    createdAt: "2025-10-01",
    updatedAt: "2025-12-20",
  },
  {
    id: "ord-011",
    title: "First-Time Investor Workshop",
    type: "Workshop",
    status: "Submitted",
    budget: 5500,
    dateRangeStart: "2026-05-15",
    dateRangeEnd: "2026-06-30",
    numberOfEvents: 2,
    targetingProfile: "Young Professionals",
    targetAge: "28-40",
    targetIncome: "$75K+",
    targetRadius: "20 miles",
    campaignDetails:
      "Entry-level workshop for young professionals starting their investment journey. Topics: 401k optimization, IRA contributions, building diversified portfolio.",
    assetPreferences: ["Facebook Ads", "Instagram Ads", "Email Sequence", "Landing Page"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "ord-012",
    title: "Legacy & Estate Planning Dinner",
    type: "Dinner Event",
    status: "Draft",
    budget: 15000,
    dateRangeStart: "2026-07-15",
    dateRangeEnd: "2026-09-15",
    numberOfEvents: 1,
    targetingProfile: "Ultra HNW Prospects",
    targetAge: "55-75",
    targetIncome: "$400K+",
    targetRadius: "20 miles",
    campaignDetails:
      "Exclusive dinner for high-net-worth couples focused on multi-generational wealth transfer, trust structures, and family office services.",
    assetPreferences: ["Premium Mailer", "Personal Invitation", "Private Banking Referral", "Landing Page"],
    advisor: "Sarah Mitchell",
    createdAt: "2026-03-29",
    updatedAt: "2026-03-29",
  },
];

export const notifications: Notification[] = [
  {
    id: "n1",
    title: "Order Approved",
    message: 'Your order "Tax Planning Webinar Digital Campaign" has been approved and is ready for production.',
    type: "success",
    read: false,
    archived: false,
    link: "/orders/ord-002",
    createdAt: "2026-03-29T14:30:00Z",
  },
  {
    id: "n2",
    title: "New Registrations",
    message: "12 new registrations for Spring Retirement Workshop in the last 24 hours.",
    type: "info",
    read: false,
    archived: false,
    link: "/campaigns/c1",
    createdAt: "2026-03-29T09:15:00Z",
  },
  {
    id: "n3",
    title: "Review Required",
    message: 'Order "Estate Planning Dinner Invitations" needs your review before proceeding.',
    type: "warning",
    read: false,
    archived: false,
    link: "/orders/ord-003",
    createdAt: "2026-03-28T16:00:00Z",
  },
  {
    id: "n4",
    title: "Campaign Performance Alert",
    message: "Tax Planning Webinar series is outperforming targets by 35%. Consider increasing budget.",
    type: "info",
    read: false,
    archived: false,
    link: "/reporting",
    createdAt: "2026-03-28T11:00:00Z",
  },
  {
    id: "n5",
    title: "Asset Ready for Review",
    message: "Direct mail proof for Spring Retirement Workshop is ready for your approval.",
    type: "warning",
    read: true,
    archived: false,
    link: "/orders/ord-001",
    createdAt: "2026-03-27T10:00:00Z",
  },
  {
    id: "n6",
    title: "Campaign Completed",
    message: 'Medicare Workshop Follow-up campaign has been completed. 31 leads generated.',
    type: "success",
    read: true,
    archived: false,
    link: "/campaigns/c5",
    createdAt: "2026-03-26T15:00:00Z",
  },
  {
    id: "n7",
    title: "Budget Update",
    message: "Spring Retirement Workshop campaign has utilized 58% of allocated budget.",
    type: "info",
    read: true,
    archived: false,
    link: "/orders/ord-001",
    createdAt: "2026-03-25T09:00:00Z",
  },
  {
    id: "n8",
    title: "System Maintenance",
    message: "Scheduled maintenance window: April 5, 2026, 2:00 AM - 4:00 AM CT.",
    type: "info",
    read: true,
    archived: true,
    link: undefined,
    createdAt: "2026-03-20T12:00:00Z",
  },
  {
    id: "n9",
    title: "New Feature Available",
    message: "Enhanced reporting dashboard with export capabilities is now live!",
    type: "success",
    read: true,
    archived: true,
    link: "/reporting",
    createdAt: "2026-03-15T10:00:00Z",
  },
];

export const leads: Lead[] = [
  { id: "l1", name: "Robert Johnson", email: "rjohnson@email.com", phone: "(312) 555-0101", status: "Qualified", campaignId: "c1", createdAt: "2026-03-25" },
  { id: "l2", name: "Patricia Williams", email: "pwilliams@email.com", phone: "(312) 555-0102", status: "Contacted", campaignId: "c1", createdAt: "2026-03-24" },
  { id: "l3", name: "Michael Brown", email: "mbrown@email.com", phone: "(312) 555-0103", status: "New", campaignId: "c1", createdAt: "2026-03-28" },
  { id: "l4", name: "Linda Davis", email: "ldavis@email.com", phone: "(312) 555-0104", status: "Converted", campaignId: "c2", createdAt: "2026-03-20" },
  { id: "l5", name: "James Wilson", email: "jwilson@email.com", phone: "(312) 555-0105", status: "Qualified", campaignId: "c2", createdAt: "2026-03-22" },
  { id: "l6", name: "Barbara Moore", email: "bmoore@email.com", phone: "(312) 555-0106", status: "New", campaignId: "c2", createdAt: "2026-03-29" },
  { id: "l7", name: "David Taylor", email: "dtaylor@email.com", phone: "(312) 555-0107", status: "Contacted", campaignId: "c5", createdAt: "2026-02-22" },
  { id: "l8", name: "Susan Anderson", email: "sanderson@email.com", phone: "(312) 555-0108", status: "Converted", campaignId: "c5", createdAt: "2026-02-25" },
  { id: "l9", name: "Richard Thomas", email: "rthomas@email.com", phone: "(312) 555-0109", status: "Lost", campaignId: "c5", createdAt: "2026-02-28" },
  { id: "l10", name: "Jennifer Jackson", email: "jjackson@email.com", phone: "(312) 555-0110", status: "New", campaignId: "c1", createdAt: "2026-03-29" },
];

export const contactProfiles: ContactProfile[] = [
  { id: "cp1", name: "Sarah Mitchell", email: "sarah@advisorgroup.com", phone: "(312) 555-1000", company: "Mitchell Wealth Advisors", role: "Lead Advisor" },
  { id: "cp2", name: "Tom Reynolds", email: "tom@advisorgroup.com", phone: "(312) 555-1001", company: "Mitchell Wealth Advisors", role: "Associate Advisor" },
  { id: "cp3", name: "Lisa Park", email: "lisa@advisorgroup.com", phone: "(312) 555-1002", company: "Mitchell Wealth Advisors", role: "Client Relations Manager" },
];

export const personas: Persona[] = [
  { id: "p1", name: "Pre-Retiree Professional", description: "Working professionals 5-10 years from retirement", ageRange: "55-65", incomeRange: "$100K-$250K", interests: ["Retirement Planning", "Social Security", "Medicare"] },
  { id: "p2", name: "High Net Worth Individual", description: "Affluent individuals with significant investable assets", ageRange: "45-70", incomeRange: "$250K+", interests: ["Tax Planning", "Estate Planning", "Alternative Investments"] },
  { id: "p3", name: "Professional Woman", description: "Career-focused women planning for financial independence", ageRange: "40-60", incomeRange: "$150K+", interests: ["Investment Strategy", "Financial Independence", "Retirement Planning"] },
  { id: "p4", name: "Corporate Executive", description: "C-suite and VP-level professionals", ageRange: "40-55", incomeRange: "$300K+", interests: ["Stock Options", "Deferred Compensation", "Tax Strategy"] },
];

export const targetingProfiles: TargetingProfile[] = [
  { id: "tp1", name: "Pre-Retirees Chicago", radius: "25 miles", ageRange: "55-70", incomeRange: "$100K+", investableAssets: "$250K+", zipCodes: ["60601", "60602", "60603", "60604", "60605"] },
  { id: "tp2", name: "High Net Worth", radius: "50 miles", ageRange: "45-65", incomeRange: "$250K+", investableAssets: "$1M+", zipCodes: ["60521", "60523", "60540", "60563"] },
  { id: "tp3", name: "Ultra HNW Prospects", radius: "15 miles", ageRange: "50-70", incomeRange: "$500K+", investableAssets: "$2M+", zipCodes: ["60521", "60043", "60093"] },
  { id: "tp4", name: "Women 45-65", radius: "30 miles", ageRange: "45-65", incomeRange: "$150K+", investableAssets: "$500K+", zipCodes: ["60601", "60602", "60614", "60657"] },
  { id: "tp5", name: "Corporate Employees", radius: "10 miles", ageRange: "35-55", incomeRange: "$100K+", investableAssets: "$100K+", zipCodes: ["60601", "60602", "60603"] },
];

export const communicationProfiles: CommunicationProfile[] = [
  { id: "comm1", name: "Standard Follow-up", emailTemplate: "professional", smsEnabled: false, followUpDays: 3, reminderEnabled: true },
  { id: "comm2", name: "Aggressive Outreach", emailTemplate: "urgent", smsEnabled: true, followUpDays: 1, reminderEnabled: true },
  { id: "comm3", name: "Gentle Nurture", emailTemplate: "casual", smsEnabled: false, followUpDays: 7, reminderEnabled: false },
];

export const performanceData = [
  { month: "Oct", leads: 22, registrations: 35, conversions: 8, spend: 4200 },
  { month: "Nov", leads: 28, registrations: 42, conversions: 11, spend: 5100 },
  { month: "Dec", leads: 18, registrations: 25, conversions: 6, spend: 3800 },
  { month: "Jan", leads: 35, registrations: 52, conversions: 14, spend: 6200 },
  { month: "Feb", leads: 42, registrations: 58, conversions: 18, spend: 7500 },
  { month: "Mar", leads: 55, registrations: 78, conversions: 22, spend: 8900 },
];

export const channelPerformance = [
  { channel: "Direct Mail", leads: 85, cost: 12500, cpl: 147, conversion: 18 },
  { channel: "Facebook Ads", leads: 62, cost: 4800, cpl: 77, conversion: 12 },
  { channel: "Google Ads", leads: 45, cost: 6200, cpl: 138, conversion: 22 },
  { channel: "LinkedIn Ads", leads: 28, cost: 3500, cpl: 125, conversion: 15 },
  { channel: "Email", leads: 38, cost: 1200, cpl: 32, conversion: 25 },
  { channel: "Referral", leads: 15, cost: 0, cpl: 0, conversion: 40 },
];

export const templates: import("./types").Template[] = [
  {
    id: "t1",
    name: "Retirement Workshop Premium",
    description: "Full-service retirement planning workshop campaign with direct mail, digital ads, and follow-up sequence.",
    type: "campaign",
    eventType: "Workshop",
    usageCount: 24,
    lastUsed: "2026-03-15",
    createdAt: "2025-06-10",
    isPopular: true,
  },
  {
    id: "t2",
    name: "Tax Planning Webinar Series",
    description: "4-part webinar series covering tax optimization strategies for high-net-worth clients.",
    type: "campaign",
    eventType: "Webinar",
    usageCount: 18,
    lastUsed: "2026-03-20",
    createdAt: "2025-08-15",
    isPopular: true,
  },
  {
    id: "t3",
    name: "Exclusive Dinner Event",
    description: "Premium dinner event campaign for ultra-high-net-worth prospects with personalized invitations.",
    type: "campaign",
    eventType: "Dinner Event",
    usageCount: 12,
    lastUsed: "2026-02-28",
    createdAt: "2025-09-20",
  },
  {
    id: "t4",
    name: "Women & Wealth Seminar",
    description: "Multi-channel campaign targeting professional women with digital and traditional media.",
    type: "campaign",
    eventType: "Seminar",
    usageCount: 8,
    lastUsed: "2026-01-15",
    createdAt: "2025-10-05",
  },
  {
    id: "t5",
    name: "Lunch & Learn Quick Start",
    description: "Fast-turn lunch event for corporate employees with minimal setup.",
    type: "campaign",
    eventType: "Lunch & Learn",
    usageCount: 15,
    lastUsed: "2026-03-10",
    createdAt: "2025-07-22",
  },
  {
    id: "t6",
    name: "High-Net-Worth Outreach",
    description: "Premium direct mail and digital campaign targeting HNW individuals.",
    type: "order",
    eventType: "Workshop",
    usageCount: 31,
    lastUsed: "2026-03-25",
    createdAt: "2025-05-01",
    isPopular: true,
  },
  {
    id: "t7",
    name: "Digital-Only Webinar",
    description: "Cost-effective digital campaign with Google Ads and email sequence.",
    type: "order",
    eventType: "Webinar",
    usageCount: 22,
    lastUsed: "2026-03-18",
    createdAt: "2025-06-15",
  },
  {
    id: "t8",
    name: "Professional Direct Mail",
    description: "High-quality direct mail piece with tracking and follow-up.",
    type: "asset",
    usageCount: 45,
    lastUsed: "2026-03-22",
    createdAt: "2025-04-10",
    isPopular: true,
  },
  {
    id: "t9",
    name: "Modern Landing Page",
    description: "Responsive, conversion-optimized landing page template.",
    type: "asset",
    usageCount: 67,
    lastUsed: "2026-03-24",
    createdAt: "2025-03-01",
    isPopular: true,
  },
  {
    id: "t10",
    name: "Email Nurture Sequence",
    description: "6-email follow-up sequence for event attendees.",
    type: "asset",
    usageCount: 38,
    lastUsed: "2026-03-21",
    createdAt: "2025-05-20",
  },
];

export const strategies: import("./types").Strategy[] = [
  {
    id: "s1",
    name: "Pre-Retiree Pipeline",
    description: "Target individuals within 5-10 years of retirement with educational workshops and personalized follow-up.",
    targetAudience: "Age 55-70, $100K+ income, $250K+ investable assets",
    recommendedChannels: ["Direct Mail", "Facebook Ads", "Email Sequence", "Landing Page"],
    expectedROI: "4.2x",
    successRate: 72,
    avgBudget: "$8,000 - $15,000",
    conversionRate: "18%",
    metrics: { leads: 850, conversion: 18, retention: 85 },
  },
  {
    id: "s2",
    name: "High-Net-Worth Acquisition",
    description: "Premium campaign targeting ultra-high-net-worth individuals through exclusive events and personalized outreach.",
    targetAudience: "Age 45-70, $500K+ income, $2M+ investable assets",
    recommendedChannels: ["Premium Direct Mail", "Personal Invitation", "LinkedIn Ads", "Phone Follow-up"],
    expectedROI: "6.5x",
    successRate: 58,
    avgBudget: "$12,000 - $25,000",
    conversionRate: "24%",
    metrics: { leads: 320, conversion: 24, retention: 92 },
  },
  {
    id: "s3",
    name: "Corporate Executive Reach",
    description: "Target C-suite and VP-level professionals with lunch & learn events and wealth management education.",
    targetAudience: "Age 40-55, $300K+ income, $500K+ investable assets",
    recommendedChannels: ["LinkedIn Ads", "Email Invitation", "Corporate Partnerships", "Webinar"],
    expectedROI: "3.8x",
    successRate: 65,
    avgBudget: "$5,000 - $10,000",
    conversionRate: "15%",
    metrics: { leads: 540, conversion: 15, retention: 78 },
  },
  {
    id: "s4",
    name: "Women Investors Focus",
    description: "Empowerment-focused campaign targeting professional women planning for financial independence.",
    targetAudience: "Age 40-60, $150K+ income, $500K+ investable assets",
    recommendedChannels: ["Facebook Ads", "Instagram Ads", "Direct Mail", "Community Partnerships"],
    expectedROI: "4.8x",
    successRate: 68,
    avgBudget: "$7,000 - $12,000",
    conversionRate: "20%",
    metrics: { leads: 420, conversion: 20, retention: 88 },
  },
  {
    id: "s5",
    name: "Digital Lead Gen",
    description: "Cost-effective digital-only campaign using Google and social media advertising.",
    targetAudience: "Age 35-65, $75K+ income, $100K+ investable assets",
    recommendedChannels: ["Google Ads", "Facebook Ads", "Landing Page", "Email Sequence"],
    expectedROI: "3.2x",
    successRate: 45,
    avgBudget: "$3,000 - $6,000",
    conversionRate: "12%",
    metrics: { leads: 1200, conversion: 12, retention: 65 },
  },
];

export const targetingInsights: import("./types").TargetingInsight[] = [
  {
    id: "ti1",
    name: "Pre-Retirees Chicago Metro",
    category: "Geographic",
    data: {
      age: "55-70",
      income: "$100K+",
      interests: ["Retirement Planning", "Social Security", "Medicare", "Estate Planning"],
      behaviors: ["Recent retirement announcements", "401k rollovers", "Pension decisions"],
    },
    performance: "excellent",
    recommendation: "Primary recommendation for workshop campaigns. High engagement and conversion rates.",
  },
  {
    id: "ti2",
    name: "High-Net-Worth Individuals",
    category: "Income",
    data: {
      age: "45-70",
      income: "$250K+",
      interests: ["Tax Planning", "Estate Planning", "Alternative Investments", "Philanthropy"],
      behaviors: ["Complex tax situations", "Business exits", "Inheritance events"],
    },
    performance: "excellent",
    recommendation: "Best for premium dinner events and personalized outreach. Highest LTV potential.",
  },
  {
    id: "ti3",
    name: "Professional Women",
    category: "Demographic",
    data: {
      age: "40-60",
      income: "$150K+",
      interests: ["Financial Independence", "Investment Strategy", "Career Growth", "Family Finance"],
      behaviors: ["Career transitions", "Divorce planning", "Inheritance"],
    },
    performance: "good",
    recommendation: "Strong potential for seminar and webinar series. Use empowering messaging.",
  },
  {
    id: "ti4",
    name: "Corporate Executives",
    category: "Professional",
    data: {
      age: "40-55",
      income: "$300K+",
      interests: ["Stock Options", "Tax Strategy", "Deferred Compensation", "Estate Planning"],
      behaviors: ["Executive transitions", "Company IPOs", "Stock vesting events"],
    },
    performance: "good",
    recommendation: "Ideal for lunch & learn and webinar formats. Focus on tax efficiency.",
  },
  {
    id: "ti5",
    name: "Suburban Families",
    category: "Lifestyle",
    data: {
      age: "35-55",
      income: "$100K+",
      interests: ["College Planning", "Home Ownership", "Family Finance", "Retirement"],
      behaviors: ["New home purchases", "College applications", "Career changes"],
    },
    performance: "average",
    recommendation: "Consider for longer-term nurturing campaigns. Lower immediate conversion.",
  },
];
